name: Generate SBOM

on:
  push:
    branches: [master]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: 'master'
        required: true

env:
  NODE_VERSION: "22.x"
  REGISTRY_URL: "https://registry.npmjs.org"
  PRODUCT_PATH: "./"
  CDXGEN_VERSION: "11.8.0"

permissions:
  contents: read

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    # if: github.event_name == 'workflow_dispatch' ||
    #   (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    outputs:
      project-version: ${{ steps.version.outputs.PROJECT_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha || github.event.inputs.version }}

      - name: Setup Node SDK
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.REGISTRY_URL }}

      - name: Install project dependencies
        run: |
          yarn install

      # - name: Update yarn version
      #   run: |
      #     yarn set version stable

      - name: Create SBOM step
        run: |
          yarn add --dev @cyclonedx/yarn-plugin-cyclonedx
          yarn exec cyclonedx-yarn --help
        # yarn dlx -q @cyclonedx/yarn-plugin-cyclonedx --output-file ${{ env.PRODUCT_PATH }}bom.json

      # - name: Extract product version
      #   id: version
      #   shell: bash
      #   run: |
      #     VERSION="$(jq -r '.metadata.component.version' < ${{ env.PRODUCT_PATH }}bom.json)"
      #     echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
      #     echo "Product version is: $VERSION"

      - name: Upload sbom
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: sbom
          path: ${{ env.PRODUCT_PATH }}bom.json
